commerce_site_homepage:
    path:     /
    defaults: { _controller: CommerceSiteBundle:Default:index }

commerce_site_accessoires:
    path:     /accessoires
    defaults: { _controller: CommerceSiteBundle:Default:accessoires }

commerce_site_maquillages:
    path:     /maquillages
    defaults: { _controller: CommerceSiteBundle:Default:maquillages }

commerce_site_tutos:
    path:     /tutos
    defaults: { _controller: CommerceSiteBundle:Default:tutos }

commerce_site_marques:
    path:     /marques
    defaults: { _controller: CommerceSiteBundle:Default:marques }

commerce_site_panier:
    path:     /panier
    defaults: { _controller: CommerceSiteBundle:Default:panier }

commerce_site_blog:
    path:     /blog
    defaults: { _controller: CommerceSiteBundle:Default:blog }

commerce_site_contacter_nous:
    path:     /contacter-nous
    defaults: { _controller: CommerceSiteBundle:Default:contacternous }

commerce_site_apropros:
    path:     /Qui-Sommes-nous
    defaults: { _controller: CommerceSiteBundle:Default:apropos }

