commerce_site:
    resource: "@CommerceSiteBundle/Resources/config/routing.yml"
    prefix:   /

commerce_user:
    resource: "@CommerceUserBundle/Resources/config/routing/all.xml"

commerce_admin_homepage:
    path:     /admin
    defaults: { _controller: CommerceAdminBundle:Admin:index}

commerce_admin_navigation:
    path:     /navigation
    defaults: { _controller: CommerceAdminBundle:Admin:navigation}

commerce_hwiconnexion:
    resource: "@CommerceHwiconnexionBundle/Resources/config/routing.xml"
    prefix:   /hwi

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login


