services:
#    commerce_admin.example:
#        class: Commerce\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     envoi.mail:
        class: Commerce\AdminBundle\Services\Mailer
        arguments: ["@mailer","@templating","@service_container"]
